<!-- =========================================================
     TESTIMONI SECTION (Versi Paling Sederhana)
========================================================= -->

<section id="testimoni-section" class="relative flex min-h-screen flex-col items-center justify-center overflow-hidden bg-[#f2ece7] py-20">
    
    <!-- Background Wave -->
    <div class="pointer-events-none absolute left-0 top-0 z-0 w-full opacity-90" aria-hidden="true">
        <svg viewBox="0 0 1440 320" class="h-auto w-full" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0,96 C300,240 500,30 800,80 C1100,130 1300,240 1440,180 L1440,0 L0,0 Z" fill="#FFFFFF" opacity="0.8"/>
            <path d="M0,110 C300,260 500,50 800,100 C1100,150 1300,260 1440,200 L1440,0 L0,0 Z" fill="#FFFFFF" opacity="0.5"/>
        </svg>
    </div>

    <!-- Container -->
    <div class="relative z-10 mx-auto w-full max-w-7xl px-4 text-center sm:px-6 lg:px-8 pt-12 md:pt-16">
        
        <!-- Header -->
        <p class="mb-2 text-sm font-semibold uppercase tracking-wider text-[#bf5f5c]">Testimoni</p>
        <h2 class="mb-6 text-4xl font-bold text-gray-900 md:text-5xl">Dari Desa untuk Desa</h2>
        <p class="mx-auto mb-12 max-w-3xl px-4 text-base leading-relaxed text-gray-600">
            Bukan sekadar janji. Desa-desa mitra kami telah merasakan perubahan besar dalam efisiensi, transparansi, dan kemudahan layanan.
        </p>

        <!-- Slider Wrapper -->
        <div id="testimonial-track-wrapper" class="relative w-full overflow-hidden rounded-2xl">
            <div id="testimonial-track" class="flex transition-transform duration-500 ease-in-out cursor-grab active:cursor-grabbing will-change-transform">
                <!-- Generated by JS -->
            </div>
        </div>

        <!-- Pagination -->
        <div id="pagination-dots" class="mt-10 flex items-center justify-center gap-3">
            <!-- Generated by JS -->
        </div>
    </div>
</section>


<!-- =========================================================
     CTA SECTION (Dengan Perbaikan Judul Satu Baris & Animasi)
========================================================= -->

<section class="relative bg-[#cc5050] py-20 md:py-24 flex items-center justify-center overflow-hidden">
    
    <div class="max-w-4xl mx-auto text-center px-4 sm:px-6 lg:px-8 relative z-10">
        
        <!-- Judul Utama: responsive, satu baris hanya di desktop -->
        <h2 class="text-3xl md:text-4xl lg:text-5xl font-bold text-white whitespace-normal md:whitespace-nowrap leading-tight mb-4 md:mb-6">
            Mulai Transformasi Desa Anda Hari Ini
        </h2>

        <!-- Deskripsi -->
        <p class="text-base md:text-lg text-white/90 max-w-2xl mx-auto mb-8 md:mb-10 leading-relaxed">
            Ubah cara desa Anda bekerja. Mulai sekarang, pelayanan publik jadi lebih cepat, efisien, dan ramah warga.
        </p>

        <!-- Tombol CTA -->
        <a href="#" class="group relative inline-block bg-[#f2d88d] text-gray-900 font-semibold px-8 py-3.5 md:px-10 md:py-4 rounded-lg shadow-md hover:shadow-[0_10px_40px_-10px_rgba(0,0,0,0.3)] transition-all duration-300 ease-in-out hover:scale-105 active:scale-95 overflow-hidden cta-fade-in-up">
            <span class="relative z-10">Hubungi Kami Sekarang</span>
            <span class="absolute inset-0 bg-gradient-to-r from-[#e6d082] to-[#f2d88d] opacity-0 group-hover:opacity-100 transition-opacity duration-300"></span>
        </a>

    </div>
</section>

<!-- =========================================================
     TESTIMONI SCRIPT - Ringkas & Stabil
========================================================= -->
<script>
document.addEventListener('DOMContentLoaded', function () {
    
    // 1. DATA
    const testimonials = [
        { cards: [
            { name: "John Doe", role: "CEO", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo." },
            { name: "Jane Smith", role: "Manager", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo." },
            { name: "Ahmad Fauzi", role: "Kepala Desa", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo." }
        ]},
        { cards: [
            { name: "Sarah Lee", role: "COO", text: "Inovasi yang dihadirkan benar-benar mengubah cara kerja tim kami. Sangat direkomendasikan untuk kemajuan desa." },
            { name: "Budi Santoso", role: "Sekretaris", text: "Transparansi dalam pengelolaan dana desa kini lebih terjamin. Sistemnya sangat user-friendly dan mudah diakses." },
            { name: "Maria R", role: "Kasir", text: "Efisiensi waktu dan tenaga meningkat drastis. Administrasi desa menjadi jauh lebih modern." }
        ]},
        { cards: [
            { name: "Rizki Aditya", role: "Pendamping Desa", text: "Pelatihan dan pendampingan dari tim sangat luar biasa. Masyarakat desa kini melek teknologi." },
            { name: "Dwi Kartika", role: "Anggota PKK", text: "Layanan yang diberikan sangat cepat dan responsif. Senang sekali menjadi mitra program ini." },
            { name: "Hendra Wijaya", role: "Tokoh Masyarakat", text: "Ini adalah langkah maju yang sangat signifikan bagi pembangunan desa di era digital." }
        ]},
        { cards: [
            { name: "Rina Maharani", role: "Bendahara Desa", text: "Sistem pelaporan keuangan menjadi jauh lebih mudah, akurat, dan cepat. Sangat membantu tugas sehari-hari saya." },
            { name: "Andi Saputra", role: "Kepala BPD", text: "Partisipasi masyarakat dalam musyawarah desa meningkat berkat transparansi data yang disajikan." },
            { name: "Sari Mulyani", role: "Staff Desa", text: "Saya sangat terbantu dengan fitur-fitur yang ada. Proses administrasi jadi sangat efisien dan tanpa ribet." }
        ]},
        { cards: [
            { name: "Joko Wiyono", role: "Ketua RT", text: "Informasi mengenai program desa tersebar dengan sangat merata. Warga menjadi lebih peduli dengan pembangunan desa." },
            { name: "Melati Putri", role: "Pengusaha Desa", text: "Kemudahan dalam mengurus perizinan berkat platform ini membuat usaha saya di desa bisa lebih cepat berkembang." },
            { name: "Irwan Hakim", role: "Guru", text: "Edukasi digital untuk masyarakat desa sangat terbantu. Anak-anak muda jadi antusias belajar teknologi baru." }
        ]},
        { cards: [
            { name: "Putri Anggraeni", role: "Penyuluh", text: "Penyuluhan pertanian dan kesehatan jadi lebih terpantau dan terdata dengan baik berkat sistem manajemen yang diberikan." },
            { name: "Bayu Segara", role: "Pemuda Desa", text: "Program ini membawa angin segar untuk pemuda desa. Banyak peluang baru yang bisa kita gali bersama." },
            { name: "Dewi Sartika", role: "Ibu Rumah Tangga", text: "Pelayanan kesehatan di posyandu jadi lebih tertib. Antrean lebih singkat dan data warga tersimpan rapi." }
        ]}
    ];

    // 2. ELEMEN & VARIABEL
    const track = document.getElementById('testimonial-track');
    const dots = document.getElementById('pagination-dots');
    const wrapWidth = () => track.parentElement.offsetWidth;
    const CLONE = testimonials.length;
    
    let curr = 0, busy = false, timer = null;
    let isDrag = false, startX = 0, startIdx = 0;

    // 3. RENDER
    function render() {
        const data = [...testimonials, testimonials[0]]; // Tambah clone pertama
        track.innerHTML = data.map(slide => `
            <div class="flex-shrink-0 w-full flex flex-nowrap items-stretch justify-center gap-4 px-4 sm:gap-6 sm:px-6">
                ${slide.cards.map(c => `
                    <div class="w-full flex-none sm:w-1/2 lg:w-1/3 flex justify-center">
                        <div class="w-full max-w-sm rounded-2xl bg-white p-6 md:p-8 flex flex-col items-center text-center shadow-[0_4px_20px_-4px_rgba(0,0,0,0.05)] testimonial-fade-in">
                            <div class="relative mb-6 h-16 w-16 md:h-20 md:w-20 overflow-hidden rounded-full bg-gray-200 border-2 border-white shadow-sm">
                                <img src="https://desaterpadu.id/wp-content/plugins/elementor/assets/images/placeholder.png" alt="${c.name}" class="h-full w-full object-cover" loading="lazy" />
                            </div>
                            <p class="mb-6 text-sm leading-relaxed text-gray-500 md:text-base">${c.text}</p>
                            <div>
                                <p class="text-sm font-bold italic text-gray-900">${c.name}</p>
                                <p class="text-xs font-medium text-gray-400">${c.role}</p>
                            </div>
                        </div>
                    </div>
                `).join('')}
            </div>
        `).join('');

        dots.innerHTML = testimonials.map((_, i) => `
            <button type="button" class="h-2.5 rounded-full transition-all duration-300 ${i === 0 ? 'w-6 bg-gray-900' : 'w-2.5 bg-gray-300'}"></button>
        `).join('');
        
        dots.querySelectorAll('button').forEach((btn, i) => {
            btn.onclick = () => { if(!busy){ stopAuto(); goTo(i); startAuto(); } };
        });
    }

    // 4. NAVIGASI
    function goTo(idx) {
        if (busy) return;
        busy = true;
        curr = idx;
        track.style.transition = 'transform 0.5s ease-in-out';
        track.style.transform = `translateX(-${idx * 100}%)`;

        const dotIdx = curr === CLONE ? 0 : curr;
        dots.querySelectorAll('button').forEach((btn, i) => {
            btn.className = `h-2.5 rounded-full transition-all duration-300 ${i === dotIdx ? 'w-6 bg-gray-900' : 'w-2.5 bg-gray-300'}`;
        });

        setTimeout(() => {
            if (curr === CLONE) {
                track.style.transition = 'none';
                track.style.transform = 'translateX(0%)';
                curr = 0;
            }
            busy = false;
        }, 550);
    }

    function nextSlide() { if (!busy) goTo(curr + 1); }

    // 5. AUTO PLAY
    function startAuto() { stopAuto(); timer = setInterval(nextSlide, 4000); }
    function stopAuto() { if (timer) { clearInterval(timer); timer = null; } }

    // 6. DRAG / SWIPE
    function getPos(e) { return e.clientX || (e.touches && e.touches[0].clientX); }
    function onStart(e) {
        if (busy) return;
        stopAuto();
        isDrag = true;
        startX = getPos(e);
        startIdx = curr;
        track.style.transition = 'none';
    }
    function onMove(e) {
        if (!isDrag) return;
        const diff = ((getPos(e) - startX) / wrapWidth()) * 100;
        track.style.transform = `translateX(${(-startIdx * 100) + diff}%)`;
    }
    function onEnd(e) {
        if (!isDrag) return;
        isDrag = false;
        const diff = (e.changedTouches ? e.changedTouches[0].clientX : e.clientX) - startX;
        const th = 50;

        if (diff < -th) goTo(startIdx + 1);
        else if (diff > th && startIdx > 0) goTo(startIdx - 1);
        else {
            track.style.transition = 'transform 0.5s ease-in-out';
            track.style.transform = `translateX(-${startIdx * 100}%)`;
            setTimeout(() => { busy = false; }, 500);
        }
        startAuto();
    }

    // 7. EVENT LISTENER
    track.addEventListener('mousedown', onStart);
    window.addEventListener('mousemove', onMove);
    window.addEventListener('mouseup', onEnd);

    track.addEventListener('touchstart', onStart, { passive: true });
    window.addEventListener('touchmove', onMove, { passive: false });
    window.addEventListener('touchend', onEnd);

    // 8. INIT
    render();
    track.style.transform = 'translateX(0%)';
    setTimeout(() => { track.style.transition = 'transform 0.5s ease-in-out'; startAuto(); }, 50);
});
</script>

<!-- =========================================================
     CUSTOM CSS
========================================================= -->
<style>
/* Animasi Testimoni */
#testimoni-section .testimonial-fade-in { animation: testimonialFadeIn 0.6s ease-in-out forwards; }
@keyframes testimonialFadeIn { from { opacity: 0; transform: translateY(12px); } to { opacity: 1; transform: translateY(0); } }
#testimoni-section #testimonial-track { user-select: none; -webkit-user-select: none; }

/* Animasi Masuk untuk Tombol CTA */
.cta-fade-in-up {
    animation: ctaFadeInUp 0.8s ease-out forwards;
}
@keyframes ctaFadeInUp {
    from { opacity: 0; transform: translateY(20px); }
    to { opacity: 1; transform: translateY(0); }
}
</style>